namespace: "default"
serviceAccount:
  name: kaas-api-service-account

ingress:
  name: "kaas-ingress"
  className: nginx

deployment:
  replicaCount: 1

  image:
    repository: kaas-api
    tag: v2.4
    pullPolicy: IfNotPresent

  containerPort: 2024

  kubeconfigPath: /root/.kube/config

  volumeMountPath: /root/.kube

  hostPath: /home/sepehr/.kube

  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "100m"

service:
  port: 2024
  targetPort: 2024
  type: NodePort

db:
  replica: 1
  maxConnections: 100
  port: 5432
  pvCapStorage: "2.5Gi"
  pvcSize: "500Mi"
  image:
    repository: "postgres"
    pullPolicy: "IfNotPresent"
